# project information
site_name: Web Client Documentation
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Map: map.md
  - Side Bar: side-bar.md
  - Customise Profile: profile.md
  - Menu: menu.md
  - Reports: reports.md
  - Alerts: alerts.md
  - Alert type: alert-types.md
  - Drivers: drivers.md
  - Groups: groups.md
  - Management: management.md
  - Odometer: odometer.md
  - Points Of Interest: poi.md
  - Users: users.md
  - Alerts: viewing-alerts.md
  
# copyright
copyright: 'Copyright &copy; 2019 Fonix Telematics Ltd'

# repository

# configuration
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'teal'
  logo:
    icon: 'help'

# customization
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/FonixTelematics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/1391224/'

# extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - toc:
      permalink: true
